### ISSUE TITLE
The status of the model is "takendown"

### ISSUE THREAD

**Issue by yingwaner** [facebookresearch/dynalab#87]
Hi,

I am a participant of the Flores task.

I passed the local and integrated tests following the model submission workflow on GitHub and submitted my model. Everything went smoothly, and I received a notification email, which said "Your model track2 has been successfully deployed. You can find and publish the model at https://dynabench.org/models/105."

but when I tried to check my results on the website, the status of our model is "takendown". 

> takendown

> The model could not be evaluated on all of the datasets. The model could have bugs.

Meanwhile, display "No data available, the model is still evaluating." at the bottom of the site.
I don't know what the problem is and I don't have any more details. What should I do to see my results?

**Comment by mazhiyi** [comment]
@gwenzek can you please look into this?

**Comment by gwenzek** [comment]
Hi @yingwaner here is the stack trace from your model:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ts/service.py", line 100, in predict
    ret = self._entry_point(input_batch, self.context)
  File "/home/model-server/tmp/models/handler.py", line 224, in handle
    input_data = _service.preprocess(data)
  File "/home/model-server/tmp/models/handler.py", line 102, in preprocess
    src_lang = example["sourceLanguage"]
```

So it seems that you have an error in your handler code that deserialize the data. Looking at the line numbers it also seems that you're not using the [suggested handler](https://github.com/facebookresearch/flores/blob/master/dynalab/handler.py)
Could you start from that one ?
Note that this handler can be run with `python handler.py` which will run some extra tests on it on top of the `dynalab-cli test --local` tests.
Does this tests pass ?

**Comment by yingwaner** [comment]
I'm not not using the suggested handler, because this is our own system, not Fairseq. I complete handle.py with the suggested template.
Can you report in more detail the cause of the error? I passed all the tests, except for the evaluation of the website.
I need more details about the error to debug.

**Comment by LesterLian** [comment]
Hi @gwenzek, can you please also look at my [submission](https://www.dynabench.org/models/122)?

It was marked "takendown" though I used the [pretrained model](https://dl.fbaipublicfiles.com/flores101/pretrained_models/flores101_mm100_175M.tar.gz), handler.py and other files suggested by the [Flores repo](https://github.com/facebookresearch/flores/tree/master/dynalab), and that I passed the local test and the `python handler.py` test.

**Comment by gwenzek** [comment]
> I'm not not using the suggested handler

There is a significant difference between the default handler suggested by dynabench and the handler [recommended for Flores](https://github.com/facebookresearch/flores/tree/master/dynalab) please look at it and in particular at the deserialization code. It also comes with extra tests for the serialization/deserialization.
You don't need to use fairseq but you need to parse the input correctly.
If you could share your handler with me it would also been helpful.

I've pasted the full stack trace error above (I missed the error message the first time, can you check again). 


@LesterLian please see #93 for more help.

**Comment by yingwaner** [comment]
I completed the handler.py of our own model by imitating the handler [recommended for Flores](https://github.com/facebookresearch/flores/tree/master/dynalab), and it passed local and integrated  test and the python handler.py test.
The model is https://www.dynabench.org/models/136
When I uploaded the model, the status was "created," and after an hour, it became "takendown." Could you please look at this [submission?](https://www.dynabench.org/models/136) 

Thank you very much!
Below is our handler.py
```
import json
import logging
import time
import os
from pathlib import Path

import torch
from typing import NamedTuple
from dynalab.handler.base_handler import BaseDynaHandler, ROOTPATH
from dynalab.tasks.flores_small2 import TaskIO


import sys
sys.path.append(ROOTPATH)
import argparse
import numpy as np
sys.path.append("..")
import sentencepiece as spm
from src.search.beam_search import beam_search
from src.data.vocab import Vocabulary
from src.utils.utility import batch_data
from src.models.encoder.sentence_rep import SentenceRepModel
from src.models.seq2seq_model import Seq2SeqModel
from src.utils.utility import str2bool

src_vocab = Vocabulary(file="vocab")
tgt_vocab = Vocabulary(file="vocab")
sp = spm.SentencePieceProcessor()
sp.Load("sentencepiece.bpe.model")
lang2code = {"eng":"_2en ", "msa":"_2ms ", "tam":"_2ta ", "tgl":"_2tl ", "ind":"_2id ", "jav":"_2jv "}


logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

# Tell Torchserve to let use do the deserialization
os.environ["TS_DECODE_INPUT_REQUEST"] = "false"


class Handler(BaseDynaHandler):

    def initialize(self, context):
        """
        load model and extra files.
        """
        logger.info(
            f"Will initialize with system_properties: {context.system_properties}"
        )
        model_pt_path, model_file_dir, device_str = self._handler_initialize(context)
        self.taskIO = TaskIO()

        checkpoint = torch.load(model_pt_path, map_location=device_str)
        self.device = device_str
        config = checkpoint['config']
        #output = open(args.output, "w") if args.output else sys.stdout

        sentenceRepModel = SentenceRepModel.build_model(config['sentenceRep'],
                                                    src_vocab)
        self.model = Seq2SeqModel(config['target'],
                         sentenceRepModel,
                         tgt_vocab=tgt_vocab)
        self.model.sentenceRep.load_state_dict(checkpoint['model_sentenceRep'])
        self.model.target.load_state_dict(checkpoint['model_target'])
        #self.model.to(torch.device(device_str))
        self.model.cuda()
        self.model.eval()
        self.initialized = True
##########

    def preprocess_one(self, example):
        """
        preprocess data into a format that the model can do inference on
        """
        # TODO: this doesn't seem to produce good results. wrong EOS / BOS ?
        src_lang = example["sourceLanguage"]
        tgt_lang = example["targetLanguage"]
        context = example["sourceText"]
        def encode(l):
            return sp.EncodeAsPieces(l)
        def encode_line(line):
            line = line.strip()
            if len(line) > 0:
                line = encode(line)
                return line

        enc_line = encode_line(context)
        input_data = lang2code[tgt_lang] + " ".join(enc_line)
        return input_data
        return example

    def preprocess(self, samples):
        input_data = [self.preprocess_one(s) for s in samples]
        return input_data
###########


    @torch.no_grad()
    def inference(self, input_data) -> list:
        src_lang_id = 0
        tgt_lang_id = 1
        input_data = input_data
        src_idx = [[src_vocab.index(w) for w in s.strip().split()] for s in input_data]
        src_len = np.array([len(s) for s in src_idx])
        idx_by_length = np.arange(len(src_len))
        candidate = {}
        batch_size = 1
        max_len_a = 1
        max_len_b = 50
        max_seq_length = 500
        length_penalty = 0.6
       
        def decode(l):
            return "".join(sp.DecodePieces(l))
        inference_output = []
        for i in range(0, len(input_data), batch_size):
            src = [src_idx[j] for j in idx_by_length[i:i + batch_size]]
            src = batch_data(src, src_vocab.pad_index, src_vocab.eos_index)
            max_len = ((src != src_vocab.pad_index).sum(-1) * max_len_a +
                       max_len_b).int()
            max_len[max_len > max_seq_length] = max_seq_length
            generated = beam_search(self.model,
                                    src=src,
                                    lang1_id=src_lang_id,
                                    lang2_id=tgt_lang_id,
                                    beam_size=5,
                                    max_len=max_len,
                                    length_penalty=length_penalty,
                                    early_stop=False)

            for k, j in enumerate(idx_by_length[i:i + batch_size]):
                hypo = []
                for w in generated[k][1:]:
                    if tgt_vocab[w.item()] == '<s>':
                        break
                    hypo.append(tgt_vocab[w.item()])
                line = " ".join(hypo)
                output = decode(line.rstrip().split())
                inference_output.append(output)
        return inference_output
        
###################


    def postprocess(self, inference_output, samples: list) -> list:
        """
        post process inference output into a response.
        response should be a list of json
        the response format will need to pass the validation in
        ```
        dynalab.tasks.flores_small1.TaskIO().verify_response(response)
        ```
        """
        translations = inference_output
        return [
            # Signing required by dynabench, don't remove.
            self.taskIO.sign_response(
                {"id": sample["uid"], "translatedText": translation},
                sample,
            )
            for translation, sample in zip(translations, samples)
        ]
#############


_service = Handler()


def deserialize(torchserve_data: list) -> list:
    samples = []
    for torchserve_sample in torchserve_data:
        data = torchserve_sample["body"]
        # In case torchserve did the deserialization for us.
        if isinstance(data, dict):
            samples.append(data)
        elif isinstance(data, (bytes, bytearray)):
            lines = data.decode("utf-8").splitlines()
            for i, l in enumerate(lines):
                try:
                    samples.append(json.loads(l))
                except Exception as e:
                    logging.error(f"Couldn't deserialize line {i}: {l}")
                    logging.exception(e)
        else:
            logging.error(f"Unexpected payload: {data}")

    return samples


def handle_mini_batch(service, samples):
    n = len(samples)
    start_time = time.time()
    input_data = service.preprocess(samples)
    logger.info(
        f"Preprocessed a batch of size {n} ({n/(time.time()-start_time):.2f} samples / s)"
    )

    start_time = time.time()
    output = service.inference(input_data)
    logger.info(
        f"Infered a batch of size {n} ({n/(time.time()-start_time):.2f} samples / s)"
    )

    start_time = time.time()
    json_results = service.postprocess(output, samples)
    logger.info(
        f"Postprocessed a batch of size {n} ({n/(time.time()-start_time):.2f} samples / s)"
    )
    return json_results


def handle(torchserve_data, context):
    if not _service.initialized:
        _service.initialize(context)
    if torchserve_data is None:
        return None

    start_time = time.time()
    all_samples = deserialize(torchserve_data)
    n = len(all_samples)
    logger.info(
        f"Deserialized a batch of size {n} ({n/(time.time()-start_time):.2f} samples / s)"
    )
    # Adapt this to your model. The GPU has 16Gb of RAM.
    batch_size = 128
    results = []
    samples = []
    for i, sample in enumerate(all_samples):
        samples.append(sample)
        if len(samples) < batch_size and i + 1 < n:
            continue

        results.extend(handle_mini_batch(_service, samples))
        samples = []

    assert len(results)
    start_time = time.time()
    response = "\n".join(json.dumps(r, indent=None, ensure_ascii=False) for r in results)
    logger.info(
        f"Serialized a batch of size {n} ({n/(time.time()-start_time):.2f} samples / s)"
    )
    return [response]


def local_test():
    from dynalab.tasks import flores_small2

    bin_data = b"\n".join(json.dumps(d).encode("utf-8") for d in flores_small2.data)
    torchserve_data = [{"body": bin_data}]

    manifest = {"model": {"serializedFile": "checkpoint.pt"}}
    system_properties = {"model_dir": ".", "gpu_id": None}

    class Context(NamedTuple):
        system_properties: dict
        manifest: dict

    ctx = Context(system_properties, manifest)
    batch_responses = handle(torchserve_data, ctx)
    print(batch_responses)

    single_responses = [
        handle([{"body": json.dumps(d).encode("utf-8")}], ctx)[0]
        for d in flores_small2.data
    ]
    assert batch_responses == ["\n".join(single_responses)]


if __name__ == "__main__":
    local_test()
```

**Comment by gwenzek** [comment]
Your last model is timing out. The current timeout is 10 minutes, I've increased it to 20. You aren't the only one seeing this.
Since most of the batches goes through, I think doubling the timeout should be fine.

The server have been redeployed, you can try re-uploading your model.
Thanks for your patience.

**Comment by yingwaner** [comment]
Thank you very much for your reply! You have solved my problem, and I can see the results of the submitted model on the website.
