### ISSUE TITLE
Large Size Model > 2GB

### ISSUE THREAD

**Issue by sbsyangjian** [facebookresearch/dynalab#91]
When I upload a large model by command "dynalab-cli upload -n t1", I met an error as below:

Config file validated
Tarballing the project directory...
Uploading file to S3...
Traceback (most recent call last):
  File "/miniconda3/envs/amlt8/bin/dynalab-cli", line 33, in <module>
    sys.exit(load_entry_point('dynalab', 'console_scripts', 'dynalab-cli')())
  File "/dynalab/dynalab_cli/main.py", line 35, in main
    command_map[args.option](args).run_command()
  File "dynalab/dynalab_cli/upload.py", line 75, in run_command
    url, files=files, data=data, headers=AccessToken().get_headers()
  File "miniconda3/envs/amlt8/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "miniconda3/envs/amlt8/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "miniconda3/envs/amlt8/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "miniconda3/envs/amlt8/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "miniconda3/envs/amlt8/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "miniconda3/envs/amlt8/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "miniconda3/envs/amlt8/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "miniconda3/envs/amlt8/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "miniconda3/envs/amlt8/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "miniconda3/envs/amlt8/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "miniconda3/envs/amlt8/lib/python3.7/http/client.py", line 1071, in _send_output
    self.send(chunk)
  File "miniconda3/envs/amlt8/lib/python3.7/http/client.py", line 993, in send
    self.sock.sendall(data)
  File "miniconda3/envs/amlt8/lib/python3.7/ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "miniconda3/envs/amlt8/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
OverflowError: string longer than 2147483647 bytes

**Comment by LesterLian** [comment]
Have you removed the old tar.gz file? I experienced the same problem even with a model smaller than 2GB. Removing that file fixed the problem.

**Comment by sbsyangjian** [comment]
Thanks ! I tried removing the old tar.gz file and can successfully upload the model file < 2GB. But how can we upload the model which is larger than the 2GB ? @LesterLian

**Comment by mazhiyi** [comment]
@sbsyangjian Did you still get the error for >2GB files after removing the `tar.gz` file? Can you please attach the error message? Thanks!

**Comment by sbsyangjian** [comment]
Hi, when I removing the old tar.gz file, I can upload the model < 2GB. But when I try to submit the M2M 615M (6GB) after removing the old tar.gz file, I also have the following error:
Ensure No *.tar.gz file in the project root dir:
ls *.tar.gz
ls: cannot access '*.tar.gz': No such file or directory

I execute "dynalab-cli upload -n t1" and still get the similar error as below:
Config file validated
Tarballing the project directory...
Uploading file to S3...
Traceback (most recent call last):
  File "/miniconda3/envs/amlt8/bin/dynalab-cli", line 33, in <module>
    sys.exit(load_entry_point('dynalab', 'console_scripts', 'dynalab-cli')())
  File "/dynalab/dynalab_cli/main.py", line 35, in main
    command_map[args.option](args).run_command()
  File "/dynalab/dynalab_cli/upload.py", line 75, in run_command
    url, files=files, data=data, headers=AccessToken().get_headers()
  File "/miniconda3/envs/amlt8/lib/python3.7/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/miniconda3/envs/amlt8/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/miniconda3/envs/amlt8/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/miniconda3/envs/amlt8/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/miniconda3/envs/amlt8/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/miniconda3/envs/amlt8/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/miniconda3/envs/amlt8/lib/python3.7/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/miniconda3/envs/amlt8/lib/python3.7/http/client.py", line 1277, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/miniconda3/envs/amlt8/lib/python3.7/http/client.py", line 1323, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/miniconda3/envs/amlt8/lib/python3.7/http/client.py", line 1272, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/miniconda3/envs/amlt8/lib/python3.7/http/client.py", line 1071, in _send_output
    self.send(chunk)
  File "/miniconda3/envs/amlt8/lib/python3.7/http/client.py", line 993, in send
    self.sock.sendall(data)
  File "/miniconda3/envs/amlt8/lib/python3.7/ssl.py", line 1034, in sendall
    v = self.send(byte_view[count:])
  File "/miniconda3/envs/amlt8/lib/python3.7/ssl.py", line 1003, in send
    return self._sslobj.write(data)
OverflowError: string longer than 2147483647 bytes

This is my config file:
{
    "task": "flores_small1",
    "checkpoint": "./model.pt",
    "handler": "handler.py",
    "requirements": false,
    "setup": true,
    "model_files": [
        "./dict.txt",
        "./sentencepiece.bpe.model"
    ],
    "exclude": []
}

**Comment by mazhiyi** [comment]
Thanks @sbsyangjian! It should be fixed by this https://github.com/facebookresearch/dynalab/pull/92

**Comment by mazhiyi** [comment]
Please pull the latest dynalab master and this issue should be resolved. @sbsyangjian Please reopen if there are still problems. Thanks!

**Comment by sbsyangjian** [comment]
@mazhiyi 
Hi I reinstall the dynalab and met a error as below:

/miniconda3/envs/dynalab/bin/dynalab-cli upload -n t1

Config file validated
Tarballing the project directory...
Uploading files to S3. For large submissions, the progress bar may hang a while even after uploading reaches 100%. Please do not kill it...
Uploading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5.22G/5.22G [09:39<00:00, 9.67MB/s]
Failed to submit model due to: 504 Server Error: Gateway Time-out for url: https://api.dynabench.org/models/upload/s3
You can inspect the prepared model submission locally at .dynalab_submissions/Jun-29-2021-11-27-13-t1.tar.gz

**Comment by mazhiyi** [comment]
@sbsyangjian Thanks for pointing this out. @TristanThrush Can you please look into the timeout error?

**Comment by mazhiyi** [comment]
Moved timeout discussion to https://github.com/facebookresearch/dynalab/issues/94 and close this one.
