### ISSUE TITLE
Help with submission

### ISSUE THREAD

**Issue by gwenzek** [facebookresearch/dynalab#93]
Hi @gwenzek, can you please also look at my [submission](https://www.dynabench.org/models/122)?

It was marked "takendown" though I used the [pretrained model](https://dl.fbaipublicfiles.com/flores101/pretrained_models/flores101_mm100_175M.tar.gz), handler.py and other files suggested by the [Flores repo](https://github.com/facebookresearch/flores/tree/master/dynalab), and that I passed the local test and the `python handler.py` test.

_Originally posted by @LesterLian in https://github.com/facebookresearch/dynalab/issues/87#issuecomment-869172888_

**Comment by gwenzek** [comment]
@LesterLian can you confirm the name of your model ? Is it "example" ?

I think there is an  issue with the "model_generation.json". It seems to not be uploaded to dynabench.
Can you share with me the content of `.dynalab/*/setup_config.json` (where * is the name of your model) ?

```
2021-06-27 06:00:36,581 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG - Backend worker process died.
--
2021-06-27 06:00:36,581 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG - Traceback (most recent call last):
2021-06-27 06:00:36,581 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.6/dist-packages/ts/model_service_worker.py", line 182, in <module>
2021-06-27 06:00:36,581 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -     worker.run_server()
2021-06-27 06:00:36,582 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.6/dist-packages/ts/model_service_worker.py", line 154, in run_server
2021-06-27 06:00:36,582 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -     self.handle_connection(cl_socket)
2021-06-27 06:00:36,582 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.6/dist-packages/ts/model_service_worker.py", line 116, in handle_connection
2021-06-27 06:00:36,582 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -     service, result, code = self.load_model(msg)
2021-06-27 06:00:36,582 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.6/dist-packages/ts/model_service_worker.py", line 89, in load_model
2021-06-27 06:00:36,582 [INFO ] epollEventLoopGroup-5-4 org.pytorch.serve.wlm.WorkerThread - 9000 Worker disconnected. WORKER_STARTED
2021-06-27 06:00:36,582 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -     service = model_loader.load(model_name, model_dir, handler, gpu, batch_size, envelope)
2021-06-27 06:00:36,582 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.6/dist-packages/ts/model_loader.py", line 110, in load
2021-06-27 06:00:36,583 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -     initialize_fn(service.context)
2021-06-27 06:00:36,583 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -   File "/usr/local/lib/python3.6/dist-packages/ts/model_loader.py", line 137, in <lambda>
2021-06-27 06:00:36,583 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -     initialize_fn = lambda ctx: entry_point(None, ctx)
2021-06-27 06:00:36,583 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/fa467b928dad42d9a8de05d757fa0ffa/handler.py", line 250, in handle
2021-06-27 06:00:36,583 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -     _service.initialize(context)
2021-06-27 06:00:36,583 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -   File "/home/model-server/tmp/models/fa467b928dad42d9a8de05d757fa0ffa/handler.py", line 80, in initialize
2021-06-27 06:00:36,583 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -     (Path(model_file_dir) / "model_generation.json").read_text()
2021-06-27 06:00:36,583 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -   File "/usr/lib/python3.6/pathlib.py", line 1196, in read_text
2021-06-27 06:00:36,583 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -     with self.open(mode='r', encoding=encoding, errors=errors) as f:
2021-06-27 06:00:36,583 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -   File "/usr/lib/python3.6/pathlib.py", line 1183, in open
2021-06-27 06:00:36,583 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -     opener=self._opener)
2021-06-27 06:00:36,583 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -   File "/usr/lib/python3.6/pathlib.py", line 1037, in _opener
2021-06-27 06:00:36,583 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -     return self._accessor.open(self, flags, mode)
2021-06-27 06:00:36,583 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -   File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
2021-06-27 06:00:36,583 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG -     return strfunc(str(pathobj), *args)
2021-06-27 06:00:36,583 [INFO ] W-9000-archive.ts1624771809-example_1.0-stdout MODEL_LOG - FileNotFoundError: [Errno 2] No such file or directory: '/home/model-server/tmp/models/fa467b928dad42d9a8de05d757fa0ffa/model_generation.json'
```

**Comment by LesterLian** [comment]
@gwenzek Thank you for your reply.
> @LesterLian can you confirm the name of your model ? Is it "example" ?

Yes. All my models are called "example", sorry about that. I'll try to name them differently.

> I think there is an issue with the "model_generation.json". It seems to not be uploaded to dynabench.

I didn't save that submission, so I submit a new one [here](https://www.dynabench.org/models/130). It's also marked "takedown". I checked the contents in the `example.tar.gz` and "model_generation.json" is there. Please help me check if it throws the same error.
```
./dict.txt
./language_pairs.txt
./model.pt
./sentencepiece.bpe.model
./handler.py
./requirements.txt
./model_generation.json
./__pycache__/
./__pycache__/handler.cpython-37.pyc
./.dynalab/
./.dynalab/example/
./.dynalab/example/setup_config.json
```
> Can you share with me the content of `.dynalab/*/setup_config.json` (where * is the name of your model) ?

```
{
    "task": "flores_small2",
    "checkpoint": "model.pt",
    "handler": "handler.py",
    "requirements": true,
    "setup": false,
    "model_files": [],
    "exclude": []
}
```
Here is the "setup_config.json" file. Do I need to explicitly include/exclude some files?

**Comment by gwenzek** [comment]
My `setup_config.json` looks like this:

```json
{
    "task": "flores_full",
    "checkpoint": "model.pt",
    "handler": "handler.py",
    "requirements": true,
    "setup": false,
    "model_files": [
        "model_generation.json",
        "dict.txt",
        "sentencepiece.bpe.model"
    ],
    "exclude": []
}
```

Can you add the files manually to `model_files` ? 
Did you run `dynalab-cli test -n example` ? this should imitate how we setup the docker instance in Dynabench and copy only the model and its dependency to the image.

**Comment by LesterLian** [comment]
> Can you add the files manually to `model_files` ?

Adding the files to `model_files` did the trick. Thank you. Essentially, we should include all files other than `handler.py`, `requirements.txt` and the model checkpoint in the config file, correct? What about internet connectivity? For example, are we able to download models from huggingface?

> Did you run `dynalab-cli test -n example` ? this should imitate how we setup the docker instance in Dynabench and copy only the model and its dependency to the image.

I guess I should really try this. Sadly, Google Colab doesn't support docker.

Thank you for all your help. I have an understanding of the submission format now.

**Comment by gwenzek** [comment]
>  What about internet connectivity? 

There is no internet connectivity. 
If you need a model from HuggingFace you'll need to download it locally first then upload it with you submission.
